export const LOG_ENRICHMENT = [
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: {
      enabled: true,
      instrumentation: true,
      key: "SENSOR_PHP_LOG_ENRICHMENT",
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "NODEJS_LOG_ENRICHMENT_UNSTRUCTURED" },
  },
  {
    schemaId: "builtin:logmonitoring.log-agent-configuration",
    schemaVersion: "1.1.12",
    scope: "environment",
    value: {
      LAConfigIISDetectionEnabled: true,
      LAConfigSystemLogsDetectionEnabled: true,
      LAConfigLogScannerLinuxNfsEnabled: false,
      LAConfigMonitorOwnLogsEnabled: true,
      LAConfigContainersLogsDetectionEnabled: true,
      LAConfigOpenLogFilesDetectionEnabled: true,
      LAConfigUTCAsDefaultContainerTimezone: true,
      LAConfigContainerTimezoneHeuristicEnabled: true,
      LAConfigDefaultTimezone: "Local time zone",
      LAConfigDateSearchLimit_Bytes: 64,
      LAConfigSeverityDetectionLimit_Bytes: 200,
      LAConfigSeverityDetectionLinesLimit: 2,
      LAConfigMaxLgisPerEntityCount: 200,
      LAConfigEventLogQueryTimeout_Sec: 5,
      LAConfigMinBinaryDetectionLimit_Bytes: 512,
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: {
      enabled: true,
      instrumentation: true,
      key: "SENSOR_DOTNET_LOG_ENRICHMENT",
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "DOTNET_LOG_ENRICHMENT_UNSTRUCTURED" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "DOTNET_LOG_ENRICHMENT_LOG4NET" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "DOTNET_LOG_ENRICHMENT_MSEXTENSIONLOGGING" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "DOTNET_LOG_ENRICHMENT_SERILOG" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: {
      enabled: true,
      instrumentation: true,
      key: "SENSOR_APACHE_LOG_ENRICHMENT",
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "GO_LOG_ENRICHMENT" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: {
      enabled: true,
      instrumentation: true,
      key: "SENSOR_JAVA_LOG_ENRICHMENT",
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "JAVA_LOG_ENRICHMENT_UNSTRUCTURED" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "LOG_ENRICHMENT_METADATA" },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: {
      enabled: true,
      instrumentation: true,
      key: "SENSOR_NGINX_LOG_ENRICHMENT",
    },
  },
  {
    schemaId: "builtin:oneagent.features",
    schemaVersion: "1.5.7",
    scope: "environment",
    value: { enabled: true, key: "NODEJS_LOG_ENRICHMENT" },
  },
]